name: duplocator ci

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core 3.1.100
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.100
    - name: Build duplocator
      run: dotnet build src/Duplocator/Duplocator.csproj --configuration Release
    - name: Build duplocator CLI
      run: dotnet build src/Duplocator.CLI/Duplocator.CLI.csproj --configuration Release
    - name: Execute tests
      run: dotnet test src/Duplocator.Test/Duplocator.Test.csproj
