name: duplocator publish
on: [push]
  #push:
    #branches: master

jobs:
  publish:
    name: Publish to nuget
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET Core 3.1.100
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.100
      - name: Publish duplocator
        uses: rohith/publish-nuget@v2
        with:
          PROJECT_FILE_PATH: src/Duplocator/Duplocator.csproj
          VERSION_FILE_PATH: src/Directory.Build.props
          VERSION_REGEX: <Version>(.*)<\/Version>
          TAG_COMMIT: false
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}
